apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090   # <-- internal DNS name,
                                                 #     same concept as
                                                 #     flask-service/redis-service
        isDefault: true
